Add preview for markdown, refactor based on new image optimizations, update configs to jupyter server, and upgrade jupyter.

diff --git a/.github/workflows/development.yaml b/.github/workflows/development.yaml
--- a/.github/workflows/development.yaml
+++ b/.github/workflows/development.yaml
@@ -1,36 +1,168 @@
-# This is a basic workflow to help you get started with Actions
-
-name: CI
-
-# Controls when the workflow will run
+name: Development
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master ]
   pull_request:
-    branches: [ master ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    strategy:
+      matrix:
+        include:
+          - distro: alpine
+            py_ver: 3.9
+          - distro: alpine
+            py_ver: 3.8
+          - distro: alpine
+            py_ver: 3.7
+          - distro: alpine
+            py_ver: 3.6
+          - distro: debian
+            py_ver: 3.9
+          - distro: debian
+            py_ver: 3.8
+          - distro: debian
+            py_ver: 3.7
+          - distro: debian
+            py_ver: 3.6
+    env:
+      DISTRO: ${{matrix.distro}}
+      PY_VER: ${{matrix.py_ver}}
+      DOCKER_CLIENT_TIMEOUT: "120"
+      COMPOSE_HTTP_TIMEOUT: "120"
+      BASE_IMAGE_HASH: "534f4bc"
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Compile image
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          docker buildx bake -f dist/${DISTRO}/docker-compose.yaml \
+              --set *.platform=linux/amd64 --set *.context=. --load
+          REF=$(eval "echo $(cat dist/${DISTRO}/docker-compose.yaml | grep 'image:' | \
+              awk '{print $2}')")
+          docker save "${REF}" | gzip > "py${PY_VER}-${DISTRO}.tar.gz"
+      - name: Add image artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: ${{format('py{0}-{1}', matrix.py_ver, matrix.distro)}}
+          path: >
+            ${{format('py{0}-{1}.tar.gz', matrix.py_ver, matrix.distro)}}
+          retention-days: 1
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - distro: alpine
+            py_ver: 3.9
+          - distro: alpine
+            py_ver: 3.8
+          - distro: alpine
+            py_ver: 3.7
+          - distro: alpine
+            py_ver: 3.6
+          - distro: debian
+            py_ver: 3.9
+          - distro: debian
+            py_ver: 3.8
+          - distro: debian
+            py_ver: 3.7
+          - distro: debian
+            py_ver: 3.6
+    env:
+      DISTRO: ${{matrix.distro}}
+      PY_VER: ${{matrix.py_ver}}
+    steps:
+      - uses: actions/checkout@v2
+      - name: Fetch image artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{format('py{0}-{1}', matrix.py_ver, matrix.distro)}}
+      - name: Run integration tests
+        run: |
+          docker load < "py${PY_VER}-${DISTRO}.tar.gz"
+          tests/main.sh
+  publish:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+    needs: test
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - distro: alpine
+            py_ver: 3.9
+          - distro: alpine
+            py_ver: 3.8
+          - distro: alpine
+            py_ver: 3.7
+          - distro: alpine
+            py_ver: 3.6
+          - distro: debian
+            py_ver: 3.9
+          - distro: debian
+            py_ver: 3.8
+          - distro: debian
+            py_ver: 3.7
+          - distro: debian
+            py_ver: 3.6
+    env:
+      DISTRO: ${{matrix.distro}}
+      PY_VER: ${{matrix.py_ver}}
+      DOCKER_USERNAME: ${{secrets.docker_username}}
+      DOCKER_PASSWORD: ${{secrets.docker_password}}
+    steps:
+      - uses: actions/checkout@v2
+      - name: Fetch image artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{format('py{0}-{1}', matrix.py_ver, matrix.distro)}}
+      - name: Publish image
+        run: |
+          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+          docker load < "py${PY_VER}-${DISTRO}.tar.gz"
+          REF=$(eval "echo $(cat dist/${DISTRO}/docker-compose.yaml | grep 'image:' | \
+              awk '{print $2}')")
+          TAG=$(echo $REF | awk -F':' '{print $2}')
+          IMAGE=$(echo $REF | awk -F':' '{print $1}')
+          docker push "${IMAGE}:${TAG}"
+          docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
+          docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
+          [ "$PY_VER" == "3.9" ] && [ "$DISTRO" == "debian" ] \
+                  && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
+                  && docker push "${IMAGE}:latest" \
+              || echo "skipping 'latest' tag..."
+  publish-docs:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v1
+      - name: Build docs
+        uses: ammaraskar/sphinx-action@master
+        with:
+          docs-folder: "docs/"
+      # - name: Upload docs artifact
+      #   uses: actions/upload-artifact@v1
+      #   with:
+      #     name: docs-html
+      #     path: docs/_build/html/
+      #     retention-days: 1
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/${GITHUB_REPOSITORY}.git \
+              --branch gh-pages --single-branch gh-pages
+          rm -R gh-pages/*
+          cp -r docs/_build/html/* gh-pages/
+          cp .gitignore gh-pages/
+          touch gh-pages/.nojekyll
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add . --all
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{secrets.GITHUB_TOKEN}}
